# 线上生产环境配置
ikaros:
  domain: test.liguohao.cn
#Sl4j 默认是[INFO],开发环境设置成[DEBUG]
logging:
  level:
    cn.liguohao.ikaros: Info
  file:
    path: ${user.home}/.ikaros/logs
    name: ${logging.file.path}/ikaros.log

#Spring
spring:
  #模板引擎thymeleaf
  thymeleaf:
    prefix: file:${user.home}/.ikaros/theme/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: true
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  # Spring Data JPA
  jpa:
    database: h2
    show-sql: true
    platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:file:~/.ikaros/db/ikaros
    driver-class-name: org.h2.Driver
    username: ikaros
    password: liguohao.cn
    initialization-mode: always