# 本地开发环境配置
#Spring
spring:
  #模板引擎thymeleaf
  thymeleaf:
    prefix: classpath:/template/simple/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  # Spring Data JPA
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ikaros?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    initialization-mode: always